In [152]:
import psycopg2
import pandas as pd

In [153]:
conn = psycopg2.connect("host=127.0.0.1 dbname=AlQuran user=postgres password=admin port=5432")

In [154]:
cur = conn.cursor()

In [155]:
conn.set_session(autocommit=True)

In [156]:
try: 
    conn = psycopg2.connect("host=127.0.0.1 dbname=AlQuran user=postgres password=admin port=5432")
except psycopg2.Error as e: 
    print("Error: Could not make connection to the Postgres database")
    print(e)
    
try: 
    cur = conn.cursor()
except psycopg2.Error as e: 
    print("Error: Could not get curser to the Database")
    print(e)

conn.set_session(autocommit=True)

# CREATE TABLE 1

In [157]:
try: 
    cur.execute("CREATE TABLE IF NOT EXISTS en_rwwad (id int PRIMARY KEY, surah_id int, ayah int, text varchar);")
except psycopg2.Error as e: 
    print("Error: Issue creating table")
    print (e)

In [158]:
data = pd.read_csv(r"C:/Users/Ikmee U-daidee/BigDataEng 22/Quran.Project.csv")
df = pd.DataFrame(data)
try:
    for row in df.itertuples():
        cur.execute("INSERT INTO en_rwwad (id, surah_id, ayah, text) \
                    VALUES (%s,%s,%s,%s)", \
                    (row.id, row.surah_id, row.ayah, row.text))
except psycopg2.Error as e:
        print("Error: Inserting Rows")
        print (e)

In [159]:
try: 
    cur.execute("SELECT * FROM en_rwwad;")
    col_names = [desc[0] for desc in cur.description]
    print(col_names)
except psycopg2.Error as e: 
    print("Error: select *")
    print (e)

rows = cur.fetchall()

# convert list of tuples to pandas dataframe
df = pd.DataFrame(rows, columns=col_names)
df

['id', 'surah_id', 'ayah', 'text']

        id  surah_id  ayah                                      text
0        1         1     1    بِسۡمِ ٱللَّهِ ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ
1        2         1     2     ٱلۡحَمۡدُ لِلَّهِ رَبِّ ٱلۡعَٰلَمِينَ
2        3         1     3                   ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ
3        4         1     4                   مَٰلِكِ يَوۡمِ ٱلدِّينِ
4        5         1     5  إِيَّاكَ نَعۡبُدُ وَإِيَّاكَ نَسۡتَعِينُ
...    ...       ...   ...                                       ...
6231  6232       114     2                           مَلِكِ ٱلنَّاسِ
6232  6233       114     3                          إِلَٰهِ ٱلنَّاسِ
6233  6234       114     4        مِن شَرِّ ٱلۡوَسۡوَاسِ ٱلۡخَنَّاسِ
6234  6235       114     5   ٱلَّذِي يُوَسۡوِسُ فِي صُدُورِ ٱلنَّاسِ
6235  6236       114     6                مِنَ ٱلۡجِنَّةِ وَٱلنَّاسِ

[6236 rows x 4 columns]

# CREATE TABLE 2

In [160]:
try: 
    cur.execute("CREATE TABLE IF NOT EXISTS en_rwwad1 (surah_id int PRIMARY KEY, arabic varchar, latin varchar, english varchar, types varchar);")
except psycopg2.Error as e: 
    print("Error: Issue creating table")
    print (e)

In [161]:
data = pd.read_csv(r"C:/Users/Ikmee U-daidee/BigDataEng 22/Quran.surah.types.csv")
df = pd.DataFrame(data)
try:
    for row in df.itertuples():
        cur.execute("INSERT INTO en_rwwad1 (surah_id, arabic, latin, english, types) \
                    VALUES (%s,%s,%s,%s,%s)", \
                    (row.surah_id, row.arabic, row.latin, row.english, row.types))
except psycopg2.Error as e:
        print("Error: Inserting Rows")
        print (e)

In [162]:
try: 
    cur.execute("SELECT * FROM en_rwwad1;")
    col_names = [desc[0] for desc in cur.description]
    print(col_names)
except psycopg2.Error as e: 
    print("Error: select *")
    print (e)

rows = cur.fetchall()

# convert list of tuples to pandas dataframe
df = pd.DataFrame(rows, columns=col_names)
df

['surah_id', 'arabic', 'latin', 'english', 'types']

     surah_id         arabic        latin              english      types
0           1   سورة الفاتحة    Al-Fatiha          The Opening    Makiyah
1           2    سورة البقرة    Al-Baqara              The Cow  Madaniyah
2           3  سورة آل عمران  Aal-e-Imran  The family of Imran  Madaniyah
3           4    سورة النساء      An-Nisa            The Women  Madaniyah
4           5   سورة المائدة     Al-Maeda     The Table Spread  Madaniyah
..        ...            ...          ...                  ...        ...
109       110     سورة النصر      An-Nasr          The Succour  Madaniyah
110       111     سورة المسد    Al-Masadd            The Flame    Makiyah
111       112   سورة الإخلاص    Al-Ikhlas         Absoluteness    Makiyah
112       113     سورة الفلق     Al-Falaq        The day break    Makiyah
113       114     سورة الناس       An-Nas          The mankind    Makiyah

[114 rows x 5 columns]

# CREATE TABLE 3

In [163]:
try: 
    cur.execute("CREATE TABLE IF NOT EXISTS en_rwwad2 (id int, en_translate varchar);")
except psycopg2.Error as e: 
    print("Error: Issue creating table")
    print (e)

In [164]:
data = pd.read_csv(r"C:/Users/Ikmee U-daidee/BigDataEng 22/quran.transEN.csv")
df = pd.DataFrame(data)
try:
    for row in df.itertuples():
        cur.execute("INSERT INTO en_rwwad2 (id, en_translate) \
                    VALUES (%s,%s)", \
                    (row.id, row.en_translate))
except psycopg2.Error as e:
        print("Error: Inserting Rows")
        print (e)

In [165]:
try: 
    cur.execute("SELECT * FROM en_rwwad2;")
    col_names = [desc[0] for desc in cur.description]
    print(col_names)
except psycopg2.Error as e: 
    print("Error: select *")
    print (e)

rows = cur.fetchall()

# convert list of tuples to pandas dataframe
df = pd.DataFrame(rows, columns=col_names)
df

['id', 'en_translate']

        id                                       en_translate
0        1  In the name of Allah, the Most Compassionate, ...
1        2    All praise be to Allah, the Lord of the worlds,
2        3         the Most Compassionate, the Most Merciful,
3        4                     Master of the Day of Judgment.
4        5  You alone we worship, and You alone we ask for...
...    ...                                                ...
6231  6232                          the Sovereign of mankind,
6232  6233                                the God of mankind,
6233  6234            from the harm of the lurking whisperer,
6234  6235           who whispers into the hearts of mankind,
6235  6236                    from among jinn and mankind.â€

[6236 rows x 2 columns]

# JOIN TABLE

In [166]:
# Execute the query
cur.execute("""SELECT en_rwwad.id  ,
en_rwwad.surah_id,
en_rwwad1.arabic as Surah_arabic,
en_rwwad1.latin as  Surah_Latin,
en_rwwad1.english,
en_rwwad1.types,
en_rwwad.ayah,
en_rwwad.text  as text ,
en_rwwad2.en_translate
FROM en_rwwad1
JOIN en_rwwad ON en_rwwad1.surah_id = en_rwwad.surah_id
JOIN en_rwwad2 ON en_rwwad.id = en_rwwad2.id
""")

# Fetch the results
rows = cur.fetchall()
# Convert to a Pandas dataframe
df = pd.DataFrame(rows, columns=['index','surah_id', 'Surah_arabic', 'Surah_Latin', 'english','types','ayah','text','en_translate'])
# Print the dataframe
df

,index,surah_id,Surah_arabic,Surah_Latin,english,types,ayah,text,en_translate
0,1,1,سورة الفاتحة,Al-Fatiha,The Opening,Makiyah,1,بِسۡمِ ٱللَّهِ ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ,"In the name of Allah, the Most Compassionate, ..."
1,2,1,سورة الفاتحة,Al-Fatiha,The Opening,Makiyah,2,ٱلۡحَمۡدُ لِلَّهِ رَبِّ ٱلۡعَٰلَمِينَ,"All praise be to Allah, the Lord of the worlds,"
2,3,1,سورة الفاتحة,Al-Fatiha,The Opening,Makiyah,3,ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ,"the Most Compassionate, the Most Merciful,"
3,4,1,سورة الفاتحة,Al-Fatiha,The Opening,Makiyah,4,مَٰلِكِ يَوۡمِ ٱلدِّينِ,Master of the Day of Judgment.
4,5,1,سورة الفاتحة,Al-Fatiha,The Opening,Makiyah,5,إِيَّاكَ نَعۡبُدُ وَإِيَّاكَ نَسۡتَعِينُ,"You alone we worship, and You alone we ask for..."
...,...,...,...,...,...,...,...,...,...
6231,6232,114,سورة الناس,An-Nas,The mankind,Makiyah,2,مَلِكِ ٱلنَّاسِ,"the Sovereign of mankind,"
6232,6233,114,سورة الناس,An-Nas,The mankind,Makiyah,3,إِلَٰهِ ٱلنَّاسِ,"the God of mankind,"
6233,6234,114,سورة الناس,An-Nas,The mankind,Makiyah,4,مِن شَرِّ ٱلۡوَسۡوَاسِ ٱلۡخَنَّاسِ,"from the harm of the lurking whisperer,"
6234,6235,114,سورة الناس,An-Nas,The mankind,Makiyah,5,ٱلَّذِي يُوَسۡوِسُ فِي صُدُورِ ٱلنَّاسِ,"who whispers into the hearts of mankind,"
6235,6236,114,سورة الناس,An-Nas,The mankind,Makiyah,6,مِنَ ٱلۡجِنَّةِ وَٱلنَّاسِ,from among jinn and mankind.â€

# Question & Answer

### Which surah that have 'wisdom'  - حِكۡمَةَ -

In [167]:
df1 = df[df['en_translate'].str.contains('wisdom')]
df1

,index,surah_id,Surah_arabic,Surah_Latin,english,types,ayah,text,en_translate
137,136,2,سورة البقرة,Al-Baqara,The Cow,Madaniyah,129,رَبَّنَا وَٱبۡعَثۡ فِيهِمۡ رَسُولٗا مِّنۡهُمۡ ...,"Our Lord, send among them a messenger to recit..."
265,258,2,سورة البقرة,Al-Baqara,The Cow,Madaniyah,251,فَهَزَمُوهُم بِإِذۡنِ ٱللَّهِ وَقَتَلَ دَاوُۥد...,"Thus they defeated them by Allahâ€™s grace, an..."
283,276,2,سورة البقرة,Al-Baqara,The Cow,Madaniyah,269,يُؤۡتِي ٱلۡحِكۡمَةَ مَن يَشَآءُۚ وَمَن يُؤۡتَ...,He gives wisdom to whom He wills; and whoever ...
349,341,3,سورة آل عمران,Aal-e-Imran,The family of Imran,Madaniyah,48,وَيُعَلِّمُهُ ٱلۡكِتَٰبَ وَٱلۡحِكۡمَةَ وَٱلتَّ...,"And He will teach him writing and wisdom, the ..."
379,372,3,سورة آل عمران,Aal-e-Imran,The family of Imran,Madaniyah,79,مَا كَانَ لِبَشَرٍ أَن يُؤۡتِيَهُ ٱللَّهُ ٱلۡك...,It is not for a human being whom Allah has giv...
381,374,3,سورة آل عمران,Aal-e-Imran,The family of Imran,Madaniyah,81,وَإِذۡ أَخَذَ ٱللَّهُ مِيثَٰقَ ٱلنَّبِيِّـۧنَ ...,And [remember] when Allah took the covenant of...
555,547,4,سورة النساء,An-Nisa,The Women,Madaniyah,54,أَمۡ يَحۡسُدُونَ ٱلنَّاسَ عَلَىٰ مَآ ءَاتَىٰه...,Or do they envy people for what Allah has give...
789,779,5,سورة المائدة,Al-Maeda,The Table Spread,Madaniyah,110,إِذۡ قَالَ ٱللَّهُ يَٰعِيسَى ٱبۡنَ مَرۡيَمَ ٱذ...,"Then Allah will say, â€œO Jesus, son of Mary, ..."
885,878,6,سورة الأنعام,Al-Anaam,The cattle,Makiyah,89,أُوْلَـٰٓئِكَ ٱلَّذِينَ ءَاتَيۡنَٰهُمُ ٱلۡكِتَ...,"They are those whom We gave the Scripture, wis..."
1374,1365,10,سورة يونس,Yunus,Jonah,Makiyah,1,الٓرۚ تِلۡكَ ءَايَٰتُ ٱلۡكِتَٰبِ ٱلۡحَكِيمِ,Alif LÄm Ra. These are the verses of the Book...
1627,1618,12,سورة يوسف,Yusuf,Joseph,Makiyah,22,وَلَمَّا بَلَغَ أَشُدَّهُۥٓ ءَاتَيۡنَٰهُ حُكۡم...,"When he reached his prime, We gave him wisdom ..."
2036,2026,16,سورة النحل,An-Nahl,The Bee,Makiyah,125,ٱدۡعُ إِلَىٰ سَبِيلِ رَبِّكَ بِٱلۡحِكۡمَةِ وَٱ...,Call to the way of your Lord with wisdom and g...
2079,2068,17,سورة الإسراء,Al-Isra,The night journey,Makiyah,39,ذَٰلِكَ مِمَّآ أَوۡحَىٰٓ إِلَيۡكَ رَبُّكَ مِن...,This is part of the wisdom that your Lord has ...
2272,2262,19,سورة مريم,Maryam,Mary,Makiyah,12,يَٰيَحۡيَىٰ خُذِ ٱلۡكِتَٰبَ بِقُوَّةٖۖ وَءَاتَ...,"[Allah said], â€œO John, hold the Scripture wi..."
2962,2953,26,سورة الشعراء,Ash-Shuara,The Poets,Makiyah,21,فَفَرَرۡتُ مِنكُمۡ لَمَّا خِفۡتُكُمۡ فَوَهَبَ ...,So I fled from you in fear. Then my Lord gave ...
3272,3266,28,سورة القصص,Al-Qasas,The Story,Makiyah,14,وَلَمَّا بَلَغَ أَشُدَّهُۥ وَٱسۡتَوَىٰٓ ءَاتَي...,When he reached his full strength and maturity...
3479,3471,31,سورة لقمان,Luqman,Luqman,Makiyah,2,تِلۡكَ ءَايَٰتُ ٱلۡكِتَٰبِ ٱلۡحَكِيمِ,"These are the verses of the Book of wisdom,"
3488,3481,31,سورة لقمان,Luqman,Luqman,Makiyah,12,وَلَقَدۡ ءَاتَيۡنَا لُقۡمَٰنَ ٱلۡحِكۡمَةَ أَنِ...,"Indeed, We endowed LuqmÄn with wisdom, [sayin..."
3575,3567,33,سورة الأحزاب,Al-Ahzab,The Coalition,Madaniyah,34,وَٱذۡكُرۡنَ مَا يُتۡلَىٰ فِي بُيُوتِكُنَّ مِنۡ...,And remember what is recited in your homes of ...
3718,3707,36,سورة يس,Ya Seen,Ya Seen,Makiyah,2,وَٱلۡقُرۡءَانِ ٱلۡحَكِيمِ,"By the Qurâ€™an, full of wisdom,"
3991,3990,38,سورة ص,Sad,Sad,Makiyah,20,وَشَدَدۡنَا مُلۡكَهُۥ وَءَاتَيۡنَٰهُ ٱلۡحِكۡمَ...,"We strengthened his kingdom, and gave him wisd..."
4272,4418,44,سورة الدخان,Ad-Dukhan,The Smoke,Makiyah,4,فِيهَا يُفۡرَقُ كُلُّ أَمۡرٍ حَكِيمٍ,"On that night, every matter of wisdom is deter..."
4333,4329,43,سورة الزخرف,Az-Zukhruf,Ornaments of Gold,Makiyah,4,وَإِنَّهُۥ فِيٓ أُمِّ ٱلۡكِتَٰبِ لَدَيۡنَا لَع...,and it is in the Master Book [Preserved Tablet...
4393,4388,43,سورة الزخرف,Az-Zukhruf,Ornaments of Gold,Makiyah,63,وَلَمَّا جَآءَ عِيسَىٰ بِٱلۡبَيِّنَٰتِ قَالَ ...,"When Jesus came with clear signs, he said, â€œ..."
4489,4489,45,سورة الجاثية,Al-Jathiya,Crouching,Makiyah,16,وَلَقَدۡ ءَاتَيۡنَا بَنِيٓ إِسۡرَـٰٓءِيلَ ٱلۡك...,"Indeed, We gave the Children of Israel the Scr..."
4853,4851,54,سورة القمر,Al-Qamar,The moon,Makiyah,5,حِكۡمَةُۢ بَٰلِغَةٞۖ فَمَا تُغۡنِ ٱلنُّذُرُ,"which contain extensive wisdom, but the warnin..."

### Surah with more than 200 ayah

In [168]:
import pandas as pd

# Execute the query
cur.execute("""SELECT en_rwwad1.surah_id, en_rwwad1.arabic as Surah_arabic, COUNT(*) AS ayah_count
               FROM en_rwwad1
               JOIN en_rwwad ON en_rwwad1.surah_id = en_rwwad.surah_id
               GROUP BY en_rwwad1.surah_id
               HAVING COUNT(*) > 200
               ORDER BY COUNT(*) DESC
            """)

# Fetch the results
rows = cur.fetchall()

# Create a DataFrame from the results
df = pd.DataFrame(rows, columns=['surah_id', 'Surah_arabic', 'ayah_count'])

# Print the DataFrame
df

   surah_id  Surah_arabic  ayah_count
0         2   سورة البقرة         286
1        26  سورة الشعراء         227
2         7  سورة الأعراف         206

### The most frequently mentioned text

#### in en_translate

In [169]:
# Execute the query
cur.execute("SELECT en_translate, COUNT(*) as count FROM en_rwwad2 GROUP BY en_translate ORDER BY count DESC LIMIT 1")

# Fetch the result
result = cur.fetchone()

# Print the result
print("The most frequently mentioned text in en_translate is:", result[0], "with", result[1], "occurrences.")

The most frequently mentioned text in en_translate is: Then which of the favors of your Lord will you [men and jinn] deny? with 31 occurrences.

#### in arabic

In [170]:
# Execute the query
cur.execute("SELECT text, COUNT(*) as count FROM en_rwwad GROUP BY text ORDER BY count DESC LIMIT 1")

# Fetch the result
result = cur.fetchone()

# Print the result
print("The most frequently mentioned text in arabic is:", result[0], "with", result[1], "occurrences.")

The most frequently mentioned text in arabic is: فَبِأَيِّ ءَالَآءِ رَبِّكُمَا تُكَذِّبَانِ with 31 occurrences.

### The most common word

#### in the text

In [171]:
from collections import Counter

# Execute the query to get all Arabic words in the en_rwwad1 table
cur.execute("SELECT text FROM en_rwwad")

# Fetch all the rows as a list of tuples
rows = cur.fetchall()

# Flatten the list of tuples into a single list of words
words = [word for row in rows for word in row[0].split()]

# Count the frequency of each word and get the most common word
most_common_word = Counter(words).most_common(1)[0]

# Print the most common word and its frequency
print("The most common word in the text column is '{}', with a frequency of {}".format(most_common_word[0], most_common_word[1]))

The most common word in the text column is 'فِي', with a frequency of 1098

#### in the en_translate

In [172]:
from collections import Counter

# Execute the query to get all Arabic words in the en_rwwad2 table
cur.execute("SELECT en_translate FROM en_rwwad2")

# Fetch all the rows as a list of tuples
rows = cur.fetchall()

# Flatten the list of tuples into a single list of words
words = [word for row in rows for word in row[0].split()]

# Count the frequency of each word and get the most common word
most_common_word = Counter(words).most_common(1)[0]

# Print the most common word and its frequency
print("The most common word in the text column is '{}', with a frequency of {}".format(most_common_word[0], most_common_word[1]))

The most common word in the text column is 'the', with a frequency of 6510

### which surah that have ٱلۡحَمۡدُ لِلَّهِ

In [173]:
# Execute the query
cur.execute("""SELECT en_rwwad1.arabic as Surah_arabic, en_rwwad.text
               FROM en_rwwad1
               JOIN en_rwwad ON en_rwwad1.surah_id = en_rwwad.surah_id
               WHERE en_rwwad.text LIKE '%ٱلۡحَمۡدُ لِلَّهِ%'
            """)

# Fetch the results
rows = cur.fetchall()

# Convert to a Pandas dataframe
df = pd.DataFrame(rows, columns=['Surah_arabic', 'text'])

# Print the dataframe
df

     Surah_arabic                                               text
0    سورة الفاتحة              ٱلۡحَمۡدُ لِلَّهِ رَبِّ ٱلۡعَٰلَمِينَ
1    سورة الأنعام  ٱلۡحَمۡدُ لِلَّهِ ٱلَّذِي خَلَقَ ٱلسَّمَٰوَٰتِ...
2    سورة الأنعام  فَقُطِعَ دَابِرُ ٱلۡقَوۡمِ ٱلَّذِينَ ظَلَمُواْ...
3    سورة الأعراف  وَنَزَعۡنَا مَا فِي صُدُورِهِم مِّنۡ غِلّٖ تَج...
4       سورة يونس  دَعۡوَىٰهُمۡ فِيهَا سُبۡحَٰنَكَ ٱللَّهُمَّ وَت...
5    سورة إبراهيم  ٱلۡحَمۡدُ لِلَّهِ ٱلَّذِي وَهَبَ لِي عَلَى ٱلۡ...
6      سورة النحل  ۞ضَرَبَ ٱللَّهُ مَثَلًا عَبۡدٗا مَّمۡلُوكٗا لّ...
7    سورة الإسراء  وَقُلِ ٱلۡحَمۡدُ لِلَّهِ ٱلَّذِي لَمۡ يَتَّخِذ...
8      سورة الكهف  ٱلۡحَمۡدُ لِلَّهِ ٱلَّذِيٓ أَنزَلَ عَلَىٰ عَبۡ...
9   سورة المؤمنون  فَإِذَا ٱسۡتَوَيۡتَ أَنتَ وَمَن مَّعَكَ عَلَى ...
10     سورة النمل  وَلَقَدۡ ءَاتَيۡنَا دَاوُۥدَ وَسُلَيۡمَٰنَ عِل...
11     سورة النمل  قُلِ ٱلۡحَمۡدُ لِلَّهِ وَسَلَٰمٌ عَلَىٰ عِبَاد...
12     سورة النمل  وَقُلِ ٱلۡحَمۡدُ لِلَّهِ سَيُرِيكُمۡ ءَايَٰتِه...
13  سورة العنكبوت  وَلَئِن سَأَلۡتَهُم مَّن نَّزَّلَ مِنَ ٱلسَّمَ...
14     سورة لقمان  وَلَئِن سَأَلۡتَهُم مَّنۡ خَلَقَ ٱلسَّمَٰوَٰتِ...
15       سورة سبأ  ٱلۡحَمۡدُ لِلَّهِ ٱلَّذِي لَهُۥ مَا فِي ٱلسَّم...
16      سورة فاطر  ٱلۡحَمۡدُ لِلَّهِ فَاطِرِ ٱلسَّمَٰوَٰتِ وَٱلۡأ...
17      سورة فاطر  وَقَالُواْ ٱلۡحَمۡدُ لِلَّهِ ٱلَّذِيٓ أَذۡهَبَ...
18   سورة الصافات            وَٱلۡحَمۡدُ لِلَّهِ رَبِّ ٱلۡعَٰلَمِينَ
19     سورة الزمر  ضَرَبَ ٱللَّهُ مَثَلٗا رَّجُلٗا فِيهِ شُرَكَآ...
20     سورة الزمر  وَقَالُواْ ٱلۡحَمۡدُ لِلَّهِ ٱلَّذِي صَدَقَنَا...
21     سورة الزمر  وَتَرَى ٱلۡمَلَـٰٓئِكَةَ حَآفِّينَ مِنۡ حَوۡل...
22      سورة غافر  هُوَ ٱلۡحَيُّ لَآ إِلَٰهَ إِلَّا هُوَ فَٱدۡعُ...

### Surah with the smallest and  largest number of ayahs

#### Surah with the smallest

In [174]:
# Surah with the smallest number of ayahs
cur.execute("""SELECT arabic, COUNT(*) as num_ayahs
               FROM en_rwwad
               JOIN en_rwwad1 ON en_rwwad.surah_id = en_rwwad1.surah_id
               GROUP BY arabic
               ORDER BY num_ayahs ASC
               LIMIT 1""")
smallest_surah = cur.fetchone()
print("Surah with the smallest number of ayahs: ", smallest_surah[0])
print("Number of ayahs in surah: ", smallest_surah[1])

Surah with the smallest number of ayahs:  سورة الكوثر
Number of ayahs in surah:  3

#### Surah with the largest

In [176]:
import pandas as pd

# Surah with the largest number of ayahs
cur.execute("""SELECT arabic, COUNT(*) as num_ayahs
               FROM en_rwwad
               JOIN en_rwwad1 ON en_rwwad.surah_id = en_rwwad1.surah_id
               GROUP BY arabic
               ORDER BY num_ayahs DESC
               LIMIT 1""")
largest_surah = cur.fetchone()
print("Surah with the largest number of ayahs: ", largest_surah[0])
print("Number of ayahs in surah: ", largest_surah[1])

Surah with the largest number of ayahs:  سورة البقرة
Number of ayahs in surah:  286

In [ ]:
try: 
    conn.close()
except psycopg2.Error as e:
    print(e)